### ISSUE TITLE
jenkins server 2.263.4 security vulnerabilities 

### ISSUE THREAD

**Issue by AnuragBhv** [jelastic-jps/jenkins#20]
Please update the docker image to use latest jenkins server 2.289.1. The current jenkins server image by jelastic has 2.263.4 version. 
Refer below image for security warning.
![image](https://user-images.githubusercontent.com/48172824/121869381-9dcbee00-cd1f-11eb-9dc9-f9c3cd9cbbcc.png)

**Comment by DmytroZubelevych** [comment]
Thank you for the valuable info,
The most up-to-date version of Jenkins will be available for Jelastic users by the end of the week.

**Comment by DmytroZubelevych** [comment]
The most up-to-date 2.289.1 version is available. Please feel free to use it.

**Comment by AnuragBhv** [comment]
Thanks for the quick support, I am using the latest one and it gives me ability to use the latest jenkins plugin also there is no more security vulnerabilities.
